server:
  port: 8000
spring:
  application:
    name: shortUrl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/short
    username: root
    password: 123
  mvc:
    static-path-pattern: /static/**
mybatis-plus:
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: 'null'
  global-config:
    db-config:
      id-type: auto